name: Workflow for CI/CD

on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  node_modules:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install node dependencies
        run: yarn

  build:
    runs-on: ubuntu-latest
    needs: [node_modules]
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Run TypeScript check
        run: npx tsc
      - name: Compile Typescript
        run: yarn build
